[tool.poetry]
name = "openmp"
version = "0.1.0"
description = ""
authors = ["Paxwell-Paxwell <pompom231245@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
